---
- name: "Setting ntp and install promox in debian"
  hosts: pve
  become: true
  roles:
    - role: geerlingguy.ntp
      vars:
        ntp_manage_config: true
        ntp_servers:
          - tw.pool.ntp.org,
          - watch.stdtime.gov.tw
          - jp.pool.ntp.org,
          - asia.pool.ntp.org,
          - time1.google.com

    - role: lae.proxmox
      vars:
        pve_group: all
        pve_reboot_on_kernel_update: true
        pve_zfs_enabled: yes
